### PR TITLE
Add debug impl for AtomicRefCell

### PR DESCRIPTION
**Pull request by Manishearth**
Needed to be able to easily put it inside structs.

### CODE REVIEW

**Comment by bholley** [comment]
Yeah, the panic issue is the reason I didn't implement this.

The simplest thing is just to avoid debug-printing the contents, and just print out "AtomicRefCell {...}" explicitly. If we wanted to do something more clever, we could add a try_borrow method, and use that, with a string fallback.

**Comment by Manishearth** [comment]
wfm

**Comment by Manishearth** [comment]
done

I didn't end up using this, but would be nice to have next time someone needs it.

**Pull request merged**
