### PR TITLE
Make this crate usable without std.

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by bholley** [comment]
The `ForceAbort` thing is a nice trick, but seems like we should really just expose the same mechanism via `core`. Is there an issue / discussion on for that? If not, could you please create one and link to it here?

Thanks for the patches!

**Comment by m-ou-se** [comment]
Not sure if it makes sense to put this in core. What happens here in this crate is technically unsafe, as there is no guarantee that the abort/exit/double-panic happens in time before another thread gets the result of the overflow and does unsound stuff.

Do you think there are situations where an `abort()` would be needed over a (potentially unwinding) `panic()` to properly guarantee soundness?

Since in this particular case the probability of the unsoundness happening is insignificantly small, I think a hack like this is 'okay'. The code here is a best effort at preventing unsoundness, but didn't and still doesn't make strict guarantees.

**Comment by m-ou-se** [comment]
Also, I don't think this can be done in `core` right now. The 'double panic means abort' is a guarantee by `std`, not by `core` or any other part. Practically all `#[no_std]` binaries use `panic = abort`. And if they don't, `core` has no way of telling the environment to abort.

**Comment by m-ou-se** [comment]
> [...] `core` has no way of telling the environment to abort.

Looks like I was wrong: [`core::intrinsics::abort`](https://doc.rust-lang.org/stable/core/intrinsics/fn.abort.html).

No clue what it does on bare metal platforms though. Maybe just an illegal instruction?

**Comment by bholley** [comment]
I'd guess it's an illegal instruction, would be straightforward to verify. My point is that this hack clearly compiles down to _something_ in `no_std` builds, and it would be nice to at least have a discussion somewhere about how we could expose that more directly.

**Comment by bholley** [comment]
And while I generally don't think this particular abort is very important, it's nice to be able to support `no_std` without making compromises to the existing code, which is exactly what your patch does. It would just be even nicer to express that with fewer characters. :-)

**Comment by m-ou-se** [comment]
Filed https://github.com/rust-lang/rust/issues/67952

**Comment by bholley** [comment]
Thanks! Please update this PR to reference that issue in the comment and then I'll merge and publish it.

**Comment by bholley** [comment]
Thanks for the patch!

**Comment by bholley** [comment]
Published as https://crates.io/crates/atomic_refcell/0.1.6

**Pull request merged**
