### PR TITLE
feat: add the immutable version of get_mut

### PR DESCRIPTION
**Pull request by aminya**

### CODE REVIEW

**Comment by bholley** [comment]
I think this is unsound:

let x = AtomicRefCell::new();
let y = x.get();
let z = x.borrow_mut(); // Mutable aliasing

Note that RefCell similarly has get_mut() but not get(). The |&mut self| creates exclusivity which prevents callers from invoking any of the dynamic borrow routines until it goes out of scope.

**Comment by aminya** [comment]
Thanks. As an alternative, using `try_borrow().unchecked_unwrap()` has the same result.

**Comment by bholley** [comment]
Hm, why do that rather than just invoking borrow(), which is equally performant and fully safe?

**Comment by aminya** [comment]
`unchecked_unwrap` still panics in the debug mode and for the tests. In the release mode, I am sure that the code works properly, so I do not need the extra panic message.

**Comment by bholley** [comment]
I would be hesitant to rely too much on dynamic analysis to conclude that code is race-free.

In any case though, is your concern the performance overhead of the dynamic check? Because try_borrow() still does the check.

**Comment by aminya** [comment]
> I would be hesitant to rely too much on dynamic analysis to conclude that code is race-free.
> 
> In any case though, is your concern the performance overhead of the dynamic check? Because try_borrow() still does the check.

Yes, my tests are more rigorous than Rust's static analysis. I wonder if the compiler does not optimize the if-check away. Because with `unchecked_unwrap` it expects an `Ok` value. So, theoretically, it should be able to directly return the `Ok` value. I think to ensure this is optimized away, there needs to be an `unsafe unchecked` version of the function.

**Pull request closed without merging**
